function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 14-Jul-2014 12:37:12

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Marker','.','LineStyle','none','Color',[0 0 1]);

% Create title
title('SNP\_A-1721275');

% Create xlabel
xlabel('log(allele A intensity)');

% Create ylabel
ylabel('log(allele B intensity)');

% Create textarrow
annotation(figure1,'textarrow',[0.4921875 0.568359375],...
    [0.309895833333333 0.348958333333333],'TextEdgeColor','none',...
    'String',{'genotype AA cluster'});

% Create textarrow
annotation(figure1,'textarrow',[0.54296875 0.541015625],...
    [0.496395833333333 0.580729166666667],'TextEdgeColor','none',...
    'String',{'genotype AB cluster'});

% Create textarrow
annotation(figure1,'textarrow',[0.302734375 0.29296875],...
    [0.6630625 0.739583333333333],'TextEdgeColor','none',...
    'String',{'genotype BB cluster'});

