function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 18-Jun-2014 22:03:57

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Marker','.','LineStyle','none','Color',[0 0 1]);

% Create xlabel
xlabel({'log(allele A intensity)'});

% Create ylabel
ylabel({'log(allele B intensity)'});

% Create textarrow
annotation(figure1,'textarrow',[0.50390625 0.544921875],...
    [0.520833333333333 0.583333333333333],'TextEdgeColor','none',...
    'String',{'genotype AB cluster'});

% Create textarrow
annotation(figure1,'textarrow',[0.267578125 0.279296875],...
    [0.618791666666667 0.700520833333333],'TextEdgeColor','none',...
    'String',{'genotype BB cluster'});

% Create textarrow
annotation(figure1,'textarrow',[0.63671875 0.701171875],[0.265625 0.296875],...
    'TextEdgeColor','none',...
    'String',{'genotype AA cluster'});

